[package]
name = "neotracker"
version = "0.1.0"
edition = "2021"
description = "A no-std MOD file parser"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

