name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt-get -y update && sudo apt-get -y install build-essential pkg-config libasound2-dev 
    - name: Build
      run: |
        cargo build --examples
    - name: Test
      run: |
        cargo test
